baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Book Shore'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30

[params]
  text_color = ""
  author = "Henley"
  favicon = ""
  site_logo = ""
  description = "Book Shore - Books by Henley"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  recent_posts_number = 3
